app:
    resource: '@AppBundle/Controller/'
    type: annotation

blog_list:
    path:      /blog/{page}
    defaults:  { _controller: AppBundle:Blog:list}
    requirements:
        page: '\d+'
blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: AppBundle:Blog:show }
blog_index:
    path:      /blog
    defaults:  { _controller: AppBundle:Blog:index }
redirect_show:
    path:      /redit
    defaults:  { _controller: AppBundle:Redirect:show }	
article_show:
  path:     /articles/{_locale}/{year}/{slug}.{_format}
  defaults: { _controller: AppBundle:Article:show, _format: html }
  requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+	   
  